import { CatalogEntry, PlanResource } from "../../types/index.js";

var AWS_REG: Record<string, CatalogEntry> = {
  aws_vpc:                          {kind:"group", g:"vpc",    label:"VPC",                  icon:"i-vpc",    cat:"net",
                                      preview:["cidr_block","enable_dns_support","enable_dns_hostnames"]},
  aws_subnet:                       {kind:"group", g:"subnet", label:"Subnet",               icon:"i-subnet", cat:"net",
                                      preview:["cidr_block","availability_zone","map_public_ip_on_launch"]},

  aws_instance:                     {kind:"node", label:"EC2 Instance",        icon:"i-ec2",    cat:"compute", sub:"instance_type",
                                      preview:["instance_type","ami","availability_zone","private_ip"]},
  aws_launch_template:              {kind:"node", label:"Launch Template",     icon:"i-ec2",    cat:"compute", sub:"instance_type", scope:"region",
                                      preview:["instance_type","image_id"]},
  aws_autoscaling_group:            {kind:"node", label:"Auto Scaling Group",  icon:"i-ec2",    cat:"compute",
                                      preview:["min_size","max_size","desired_capacity"]},
  aws_internet_gateway:             {kind:"node", label:"Internet Gateway",    icon:"i-igw",    cat:"net",  scope:"vpc",
                                      preview:["vpc_id"]},
  aws_egress_only_internet_gateway: {kind:"node", label:"Egress-Only IGW",     icon:"i-igw",    cat:"net",  scope:"vpc",
                                      preview:["vpc_id"]},
  aws_nat_gateway:                  {kind:"node", label:"NAT Gateway",         icon:"i-nat",    cat:"net",
                                      preview:["subnet_id","connectivity_type","allocation_id"]},
  aws_route_table:                  {kind:"node", label:"Route Table",         icon:"i-rt",     cat:"net",  scope:"vpc",
                                      preview:["vpc_id"]},
  aws_route:                        {kind:"node", label:"Route",               icon:"i-rt",     cat:"net",  scope:"vpc",
                                      preview:["destination_cidr_block","gateway_id","nat_gateway_id"]},
  aws_vpc_endpoint:                 {kind:"node", label:"VPC Endpoint",        icon:"i-vpce",   cat:"net",  sub:"service_name",
                                      preview:["service_name","vpc_endpoint_type","vpc_id"]},
  aws_network_acl:                  {kind:"node", label:"Network ACL",         icon:"i-nacl",   cat:"sec",  scope:"vpc",
                                      preview:["vpc_id"]},
  aws_security_group:               {kind:"group", g:"sg", label:"Security Group", icon:"i-sg",  cat:"sec",  scope:"vpc"},
  /* the VPC's own default objects: Terraform adopts them rather than creating
     them, and every plan using the public VPC module has all three */
  aws_default_network_acl:          {kind:"node", label:"Default Network ACL", icon:"i-nacl",   cat:"sec",  scope:"vpc",
                                      preview:["vpc_id"]},
  aws_default_route_table:          {kind:"node", label:"Default Route Table", icon:"i-rt",     cat:"net",  scope:"vpc",
                                      preview:["default_route_table_id"]},
  aws_default_security_group:       {kind:"node", label:"Default Security Group", icon:"i-sg",  cat:"sec",  scope:"vpc",
                                      preview:["vpc_id"]},
  aws_eip:                          {kind:"node", label:"Elastic IP",          icon:"i-eip",    cat:"net",
                                      preview:["domain","public_ip","instance"]},
  aws_lb:                           {kind:"node", label:"Load Balancer",       icon:"i-lb",     cat:"net",
                                      preview:["load_balancer_type","internal"]},
  aws_alb:                          {kind:"node", label:"Load Balancer",       icon:"i-lb",     cat:"net",
                                      preview:["load_balancer_type","internal"]},
  aws_lb_target_group:              {kind:"node", label:"Target Group",        icon:"i-lb",     cat:"net",  scope:"vpc",
                                      preview:["port","protocol","target_type"]},
  aws_db_instance:                  {kind:"node", label:"RDS Instance",        icon:"i-db",     cat:"db",   sub:"engine",
                                      preview:["engine","engine_version","instance_class","allocated_storage","multi_az"]},
  aws_eks_cluster:                      {kind:"node", label:"EKS Cluster",            icon:"i-eks",    cat:"compute", sub:"version", scope:"vpc",
                                          preview:["version","role_arn","endpoint"]},
  aws_eks_node_group:                   {kind:"node", label:"EKS Node Group",         icon:"i-eks",    cat:"compute", sub:"instance_types",
                                          preview:["cluster_name","instance_types","scaling_config","capacity_type"]},
  aws_placement_group:                  {kind:"node", label:"Placement Group",        icon:"i-ec2",    cat:"compute", scope:"region",
                                          preview:["strategy"]},

  aws_ec2_transit_gateway:              {kind:"node", label:"Transit Gateway",        icon:"i-tgw",    cat:"net", scope:"region",
                                          preview:["description","amazon_side_asn","default_route_table_association"]},
  aws_ec2_transit_gateway_vpc_attachment:{kind:"assoc", label:"TGW Attachment",       icon:"i-tgw",    cat:"net",
                                          preview:["transit_gateway_id","vpc_id","subnet_ids"]},
  aws_vpc_peering_connection:           {kind:"node", label:"VPC Peering",            icon:"i-peer",   cat:"net", scope:"region",
                                          preview:["vpc_id","peer_vpc_id","auto_accept"]},
  aws_ec2_managed_prefix_list:          {kind:"node", label:"Prefix List",            icon:"i-prefix", cat:"net", scope:"region",
                                          preview:["name","address_family","max_entries"]},
  aws_route53_zone:                     {kind:"node", label:"Route 53 Zone",          icon:"i-r53",    cat:"net",
                                          preview:["name","comment"]},
  aws_route53_record:                   {kind:"node", label:"Route 53 Record",        icon:"i-r53",    cat:"net", sub:"type",
                                          preview:["zone_id","name","type","ttl","records"]},

  aws_kms_key:                          {kind:"node", label:"KMS Key",                icon:"i-kms",    cat:"sec", scope:"region",
                                          preview:["description","key_usage","deletion_window_in_days","enable_key_rotation"]},

  aws_db_subnet_group:              {kind:"node", label:"DB Subnet Group",     icon:"i-db",     cat:"db",
                                      preview:["subnet_ids"]},
  aws_db_parameter_group:           {kind:"node", label:"DB Parameter Group",  icon:"i-db",     cat:"db",   scope:"region",
                                      preview:["family","name"]},
  aws_rds_cluster:                  {kind:"node", label:"RDS Cluster",         icon:"i-db",     cat:"db",   sub:"engine",
                                      preview:["engine","engine_version","database_name"]},
  aws_s3_bucket:                    {kind:"node", label:"S3 Bucket",           icon:"i-s3",     cat:"storage", scope:"region",
                                      preview:["bucket","force_destroy"]},
  aws_s3_bucket_versioning:         {kind:"assoc", label:"S3 Versioning",      icon:"i-s3",     cat:"storage",
                                      preview:["bucket"]},
  aws_s3_bucket_server_side_encryption_configuration:{kind:"assoc", label:"S3 Encryption", icon:"i-s3", cat:"storage",
                                      preview:["bucket"]},
  aws_s3_object:                    {kind:"node", label:"S3 Object",           icon:"i-s3",     cat:"storage", sub:"key",
                                      preview:["bucket","key","content_type"]},
  aws_s3_bucket_policy:             {kind:"assoc", label:"S3 Bucket Policy",   icon:"i-s3",     cat:"storage",
                                      preview:["bucket"]},
  aws_lambda_function:              {kind:"node", label:"Lambda Function",     icon:"i-lambda", cat:"compute", sub:"runtime",
                                      preview:["runtime","handler","memory_size","timeout"]},
  aws_sqs_queue:                    {kind:"node", label:"SQS Queue",           icon:"i-sqs",    cat:"integ", scope:"region",
                                      preview:["name","fifo_queue","visibility_timeout_seconds"]},
  aws_sns_topic:                    {kind:"node", label:"SNS Topic",           icon:"i-sns",    cat:"integ", scope:"region",
                                      preview:["name","fifo_topic"]},
  aws_cloudwatch_log_group:         {kind:"node", label:"Log Group",           icon:"i-cw",     cat:"mgmt", scope:"region",
                                      preview:["retention_in_days"]},

  aws_iam_role:                     {kind:"node", label:"IAM Role",            icon:"i-iam",    cat:"sec",  scope:"global",
                                      preview:["path","max_session_duration"]},
  aws_iam_policy:                   {kind:"node", label:"IAM Policy",          icon:"i-iam",    cat:"sec",  scope:"global",
                                      preview:["path"]},
  aws_iam_role_policy:              {kind:"assoc", label:"Role Policy",        icon:"i-iam",    cat:"sec",  scope:"global",
                                      preview:["role"]},
  aws_iam_openid_connect_provider:  {kind:"node", label:"OIDC Provider",       icon:"i-iam",    cat:"sec",  scope:"global",
                                      preview:["url","client_id_list"]},
  aws_iam_instance_profile:         {kind:"node", label:"Instance Profile",    icon:"i-iam",    cat:"sec",  scope:"global",
                                      preview:["role"]},
  aws_iam_user:                     {kind:"node", label:"IAM User",            icon:"i-iam",    cat:"sec",  scope:"global",
                                      preview:["path"]},

  aws_route_table_association:          {kind:"assoc", label:"RT Association",       icon:"i-rt",  cat:"net",
                                          preview:["subnet_id","route_table_id"]},
  aws_main_route_table_association:     {kind:"assoc", label:"Main RT Association",  icon:"i-rt",  cat:"net",
                                          preview:["route_table_id"]},
  aws_network_acl_association:          {kind:"assoc", label:"NACL Association",     icon:"i-nacl",cat:"sec",
                                          preview:["subnet_id"]},
  aws_iam_role_policy_attachment:       {kind:"assoc", label:"Policy Attachment",    icon:"i-iam", cat:"sec",
                                          preview:["policy_arn"]},
  aws_iam_user_policy_attachment:       {kind:"assoc", label:"Policy Attachment",    icon:"i-iam", cat:"sec",
                                          preview:["policy_arn"]},
  aws_security_group_rule:              {kind:"assoc", label:"SG Rule",              icon:"i-sg",  cat:"sec",
                                          preview:["type","from_port","to_port","protocol"]},
  aws_vpc_security_group_ingress_rule:  {kind:"assoc", label:"SG Ingress Rule",      icon:"i-sg",  cat:"sec",
                                          preview:["from_port","to_port","ip_protocol","cidr_ipv4"]},
  aws_vpc_security_group_egress_rule:   {kind:"assoc", label:"SG Egress Rule",       icon:"i-sg",  cat:"sec",
                                          preview:["from_port","to_port","ip_protocol","cidr_ipv4"]},
  aws_lb_listener:                      {kind:"assoc", label:"LB Listener",          icon:"i-lb",  cat:"net",
                                          preview:["port","protocol"]},
  aws_lb_target_group_attachment:       {kind:"assoc", label:"TG Attachment",         icon:"i-lb",  cat:"net",
                                          preview:["target_group_arn","target_id","port"]},
  aws_vpc_endpoint_route_table_association:{kind:"assoc", label:"Endpoint RT Assoc", icon:"i-vpce",cat:"net",
                                          preview:["route_table_id"]}
};

var CAT: Record<string, string> = {
  compute:  "var(--aws-compute)",
  net:      "var(--aws-net)",
  sec:      "var(--aws-sec)",
  storage:  "var(--aws-storage)",
  db:       "var(--aws-db)",
  mgmt:     "var(--aws-mgmt)",
  integ:    "var(--aws-integ)"
};

var CAT_LABEL: [string, string][] = [
  ["compute", "Compute"],
  ["net",     "Networking"],
  ["sec",     "Security & identity"],
  ["storage", "Storage"],
  ["db",      "Database"],
  ["mgmt",    "Management"],
  ["integ",   "Application integration"],
  ["other",   "Not implemented"]
];

var SIZE_H: Record<string, number> = {};

function awsBlockHeight(r: PlanResource): number {
  if (r.kind === "assoc") return 10;
  return 26;
}

export { AWS_REG, CAT, CAT_LABEL, SIZE_H, awsBlockHeight };
