import { escapeHtml } from "./util.js";
import { SENSITIVE } from "./redact.js";
import { PlanResource, TerraformConfigurationResource } from "../types/index.js";

/* ---- Terraform block, rebuilt from configuration.expressions. The plan does
   not carry source text, so interpolated values are shown resolved with the
   reference noted alongside. ---- */

function hclLit(v: any, ind: string): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  if (v === SENSITIVE) return SENSITIVE;
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)){
    if (!v.length) return "[]";
    var simple = v.every(function(x: any){ return typeof x !== "object" || x === null; });
    if (simple) return "[" + v.map(function(x: any){ return hclLit(x, ind); }).join(", ") + "]";
    return "[\n" + v.map(function(x: any){ return ind + "  " + hclLit(x, ind + "  "); }).join(",\n") + "\n" + ind + "]";
  }
  var ks = Object.keys(v);
  if (!ks.length) return "{}";
  return "{\n" + ks.map(function(k: string){
    return ind + "  " + k + " = " + hclLit(v[k], ind + "  ");
  }).join("\n") + "\n" + ind + "}";
}

function isBlockList(v: any): boolean {
  return Array.isArray(v) && v.length > 0 && v.every(function(x: any){
    return x && typeof x === "object" && !Array.isArray(x);
  });
}

/* plural id/arn/cidr attributes are lists even when the plan cannot resolve
   them yet, so a reference feeding one keeps its brackets */
var LIST_ATTR = /(_ids|_arns|_blocks|_groups|_zones|_subnets|_names)$/;

function exprVal(e: any, resolved: any, ind: string, key?: string): { txt: string; note?: string } {
  if (e && Object.prototype.hasOwnProperty.call(e, "constant_value")) return {txt:hclLit(e.constant_value, ind)};
  if (e && e.references && e.references.length){
    var refs: string[] = e.references;
    /* a resource or data source address, of any provider's type */
    var direct = refs.filter(function(x: string){ return /^(data\.)?[A-Za-z][A-Za-z0-9-]*_[A-Za-z0-9_-]+\./.test(x); });
    if (direct.length && refs.length <= 2){
      /* a reference feeding a list attribute keeps its brackets */
      var isList = Array.isArray(resolved) || (key && LIST_ATTR.test(key));
      var txt = isList ? "[" + direct[0] + "]" : direct[0];
      return {txt:txt};
    }
    if (resolved !== undefined && resolved !== null)
      return {txt:hclLit(resolved, ind), note:refs.join(", ")};
    return {txt:refs[0]};
  }
  if (resolved !== undefined && resolved !== null) return {txt:hclLit(resolved, ind)};
  return {txt:"null"};
}

function hclFor(r: PlanResource, cfg?: TerraformConfigurationResource | any): string | null {
  if (!cfg || !cfg.expressions) return null;
  var L: string[] = [];
  L.push('resource "' + r.type + '" "' + r.name + '" {');

  ["count","for_each","provider"].forEach(function(m: string){
    if ((cfg as any)[m] !== undefined){
      var v = exprVal((cfg as any)[m], undefined, "  ", m);
      L.push("  " + m + " = " + v.txt);
    }
  });

  /* cfg is an entry of model.cfgByAddr, in which the parser has already
     replaced the literals of sensitive attributes (core/redact.ts,
     redactConfig). */
  var keys = Object.keys(cfg.expressions).sort();
  var blocks: { k: string; items: any[]; wrapped: boolean }[] = [];
  keys.forEach(function(k: string){
    var e = cfg.expressions[k];
    /* terraform encodes a repeated nested block either as an array of
       expression maps, or as one constant_value holding an array of objects */
    if (Array.isArray(e)){ blocks.push({k:k, items:e, wrapped:true}); return; }
    if (e && isBlockList(e.constant_value)){ blocks.push({k:k, items:e.constant_value, wrapped:false}); return; }
    var v = exprVal(e, r.attrs ? r.attrs[k] : undefined, "  ", k);
    L.push("  " + k + " = " + v.txt + (v.note ? "  # from " + v.note : ""));
  });

  blocks.forEach(function(b){
    b.items.forEach(function(item: any){
      L.push("");
      L.push("  " + b.k + " {");
      Object.keys(item).sort().forEach(function(kk: string){
        var raw = item[kk];
        if (raw === null || raw === undefined) return;
        var v = b.wrapped ? exprVal(raw, undefined, "    ", kk)
                          : {txt: hclLit(raw, "    ")};
        if (v.txt === "null") return;
        L.push("    " + kk + " = " + v.txt);
      });
      L.push("  }");
    });
  });

  if (cfg.depends_on && cfg.depends_on.length){
    L.push("");
    L.push("  depends_on = [" + cfg.depends_on.join(", ") + "]");
  }

  L.push("}");
  return L.join("\n");
}

/* Syntax colouring for the block above. The HCL is generated by hclFor, so
   its shape is known and a line-based pass is enough: no parser needed. */

function hclValue(v: string): string {
  var out = "", re = /("(?:[^"\\]|\\.)*")|\b(true|false|null)\b|(-?\d+(?:\.\d+)?)\b|([A-Za-z_][\w-]*(?:\.[\w-]+)+)/g;
  var last = 0, m: RegExpExecArray | null;
  while ((m = re.exec(v)) !== null){
    out += escapeHtml(v.slice(last, m.index));
    if (m[1])      out += '<span class="s">' + escapeHtml(m[1]) + '</span>';
    else if (m[2]) out += '<span class="b">' + escapeHtml(m[2]) + '</span>';
    else if (m[3]) out += '<span class="n">' + escapeHtml(m[3]) + '</span>';
    else           out += '<span class="r">' + escapeHtml(m[4]) + '</span>';
    last = m.index + m[0].length;
  }
  return out + escapeHtml(v.slice(last));
}

function hclHighlight(src: string): string {
  return src.split("\n").map(function(line: string){
    /* a trailing "# from ..." note is a comment, whatever precedes it */
    var note = "", hash = line.indexOf("  # ");
    if (hash >= 0){
      note = '<span class="c">' + escapeHtml(line.slice(hash)) + '</span>';
      line = line.slice(0, hash);
    }

    var m: RegExpMatchArray | null;
    if ((m = line.match(/^(resource|data|variable|output|module)\s+("[^"]*")\s+("[^"]*")(\s*\{)$/))){
      return '<span class="k">' + m[1] + '</span> <span class="t">' + escapeHtml(m[2]) +
             '</span> <span class="s">' + escapeHtml(m[3]) + '</span>' + escapeHtml(m[4]) + note;
    }
    if ((m = line.match(/^(\s*)([\w-]+)(\s*=\s*)(.*)$/))){
      return m[1] + '<span class="a">' + escapeHtml(m[2]) + '</span>' +
             escapeHtml(m[3]) + hclValue(m[4]) + note;
    }
    if ((m = line.match(/^(\s*)([\w-]+)(\s*\{)$/))){
      return m[1] + '<span class="k">' + escapeHtml(m[2]) + '</span>' + escapeHtml(m[3]) + note;
    }
    return escapeHtml(line) + note;
  }).join("\n");
}

export { hclLit, isBlockList, exprVal, hclFor, hclValue, hclHighlight };

